### PR TITLE
Clean request after views.Endpoint.dispatch

### PR DESCRIPTION
**Pull request by SamambaMan**
After the execution of dispatch, the following code:
`request.content_type = request.META.get('CONTENT_TYPE', 'text/plain')`
The request contents (POST, body) are cleaned if the post is a multipart/form-data .

### CODE REVIEW

**Comment by senko** [comment]
@SamambaMan did you want to make a pull request from some other branch or fork? This PR (merging master into an obsolete old branch) doesn’t seem to be set up correctly.

**Comment by SamambaMan** [comment]
Senko, thank you for your attention.

It's my first contribution attempt on github, i'm a bit lost, in fact.
I checked out and locally commited my edit on the master branch.

May you please give me instructions on how to proceed?

Thanks in advance!

**Comment by senko** [comment]
The usual procedure is the following:

1. Fork this repository so you have your own copy (that you can write to) on github
2. Clone your repository so you have a local copy on your computer
3. Create a branch in local repository and add your changes there
4. Push the new branch from your local repository to your github repository
5. Make a pull request on github, asking to merge your new branch from your github repo to master here

I hope this helps!

**Comment by SamambaMan** [comment]
Helped a lot! 
Doing it right now.

Thanks!

**Pull request closed without merging**
